"""Add product url and storage 3d spatial coordinates

Revision ID: 13619e4c106a
Revises: 3372986f1e4a
Create Date: 2026-08-23 13:47:34.696439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13619e4c106a'
down_revision: Union[str, Sequence[str], None] = '3372986f1e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pos_x', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('pos_y', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('pos_z', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('size_x', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('size_y', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('size_z', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.drop_column('size_z')
        batch_op.drop_column('size_y')
        batch_op.drop_column('size_x')
        batch_op.drop_column('pos_z')
        batch_op.drop_column('pos_y')
        batch_op.drop_column('pos_x')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
