"""Change Part.attributes to JSON

Revision ID: 65df9c9ae742
Revises: 5c9d076edef0
Create Date: 2026-08-08 17:38:28.355020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65df9c9ae742'
down_revision: Union[str, Sequence[str], None] = '5c9d076edef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.alter_column('attributes',
               existing_type=sa.BLOB(),
               type_=sa.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.alter_column('attributes',
               existing_type=sa.JSON(),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
